### ISSUE TITLE
关于sql Hook问题

### ISSUE THREAD

**Issue by soulfy** [baidu/openrasp#104]
openrasp version 0.24

这两天刚开学习openrasp，写了个plugin test：
```jsx
var plugin = new RASP('lk_test')
function checkSQL(params, context) {
    var result = {
    action: 'ignore',
    message: '无风险',
    confidence: 90
}
plugin.log(params.server, params.query)
    return result
}
plugin.register('sql', checkSQL)
plugin.log('初始化成功')
```
得到的结果里只有[lk_test] mysql select @@session.tx_read_only, 没见到具体的数据库表读写，这是为什么呢？

**Comment by CaledoniaProject** [comment]
你使用的是哪种数据库？目前我们不支持 prepared statement，可能是这个原因导致的

**Comment by soulfy** [comment]
嗯， 我这里确实用了prepared statement

**Comment by soulfy** [comment]
原来[#8](https://github.com/baidu/openrasp/issues/8)里说的就是个问题
