### ISSUE TITLE
关于SSRF检测建议

### ISSUE THREAD

**Issue by Roysatm** [baidu/openrasp#105]
在源码中看到对于SSRF检测算法，感觉比较复杂并且不能完全覆盖SSRF攻击，例如八进制的主机地址、直接十进制的主机地址(http://192.168.0.1 >>> http://3232235521/)、短地址（http://dwz.cn/11SMa >>> http://127.0.0.1）。我个人认为直接使用DNS解析，把任何域名或地址统一解析成地址，从地址上进行过滤拦截更合适些。

**Comment by CaledoniaProject** [comment]
在v0.30里改进了SSRF检测算法。当请求地址解析为内网，且来自用户输入，就判定为SSRF并拦截。

https://github.com/baidu/openrasp/blob/master/plugins/official/plugin.js#L420

**Comment by CaledoniaProject** [comment]
没有其他意见的话，我先关闭 ISSUE 了
