### ISSUE TITLE
[OpenRASP] Failed to initialize, will continue without security protection

### ISSUE THREAD

**Issue by whoadmin** [baidu/openrasp#124]
# Bug report

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions

And please include the following information:
- Operating system type and architecture
- Application server type and version
  - For Java based web application servers, provide JDK version
- OpenRASP version

# Feature Request

Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- what alternatives to the feature you have considered

**Comment by CaledoniaProject** [comment]
https://github.com/baidu/openrasp/issues/98

**Comment by CaledoniaProject** [comment]
已解决，最晚下周三发版
