### ISSUE TITLE
php7支持多久发布

### ISSUE THREAD

**Issue by mienv567** [baidu/openrasp#128]

**Comment by CaledoniaProject** [comment]
预计 7.27 完成测试，目前代码在 [php-dev](https://github.com/baidu/openrasp/tree/php-dev) 分支，可自行编译测试

**Comment by Lynnjie** [comment]
关于PHP可以支持lampp吗？

**Comment by CaledoniaProject** [comment]
@Lynnjie 支持，兼容性 https://rasp.baidu.com/doc/install/compat.html#php

**Comment by CaledoniaProject** [comment]
已发布，有问题请开新的ISSUE https://rasp.baidu.com/doc/release/main.html#v40
