### ISSUE TITLE
spring boot 项目如何验证openrasp是否有效

### ISSUE THREAD

**Issue by yglong** [baidu/openrasp#138]
我已经将openrasp集成到我的项目中，spring boot项目 jar包启动模式，已经成功启动openrasp，但是我用扫描漏洞工具 还是扫描出多个跨域攻击及OPTION攻击？ 请问OpenRasp是否能有效防止这些攻击呢。因为扫描结果跟没有引入openRASP一样。请问如何验证是否集成成功？

**Comment by CaledoniaProject** [comment]
你可以看下响应里面是否包含 `X-Protected-By: OpenRASP` 来判断 OpenRASP 是否安装成功

```
curl -I 127.0.0.1:8080
```

至于扫描报告的问题，方便的话可以加下QQ群，联系群主

https://rasp.baidu.com/#section-support

**Comment by yglong** [comment]
我测试了一下，找到原因了，我的项目采用默认undertow容器，并非tomcat。貌似并不支持undertow，调整到tomcat后可以了，谢谢

**Comment by CaledoniaProject** [comment]
好的，后面我们会把 undertow 支持加到计划里
