### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by vksethi77** [baidu/openrasp#142]
I have copied the xss-demo.js code in plugin.js. I injected <script> tag - it didn't throw security exception - basically it didn't block the request. Please have a look at it. If there is something wrong, I am doing - please let me the steps to follow so that I  can stop xss

**Comment by CaledoniaProject** [comment]
By default, OpenRASP does not decode the request parameter until user-level code does it.

Try adding an encoding configuration in `<tomcat_home>rasp/conf/rasp.properties`, And the XSS demo should work for you:

```
request.param_encoding=utf-8
```

**Comment by CaledoniaProject** [comment]
The xss-demo.js filters dangerous tags with regular expressions, it only serves to be a DEMO.

We've designed a new algorithm to handle reflected XSS without signatures, it should be release in v0.41

**Comment by vksethi77** [comment]
Thanks for the reply. When v0.41 will be released?

Also,  setting  --  request.param_encoding=utf-8 to rasp.properties is
enough? or do i need to copy xss-demo.js contents also to plugin.js ?

Can you please tell what all other changes to be made to make xss demo work
?

**Comment by CaledoniaProject** [comment]
Yes, you need to place `xss-demo.js` in the plugin folder. aka `<tomcat_home>/rasp/plugins`.

I don't have an exact release time for v0.41 yet. The next release is v0.40 - PHP 7.X support.
