### ISSUE TITLE
ssrf规则bug

### ISSUE THREAD

**Issue by xiaoyanguoke** [baidu/openrasp#146]
如下图所示，在测试ssrf过程中，url=file:///etc/passwd，不会被openrasp拦截。在规则中看到对file做了检测，怎么回事
![image](https://user-images.githubusercontent.com/15224735/42929210-f639175a-8b6b-11e8-873d-83722a738cbb.png)

**Comment by CaledoniaProject** [comment]
你好，我这边测试能够拦截。是不是没装插件？加QQ群讨论吧 https://rasp.baidu.com/#section-support
