### ISSUE TITLE
express, koa, node, ...

### ISSUE THREAD

**Issue by DanielRuf** [baidu/openrasp#147]
It would be great to have support for the Node.js ecosystem so express, koa, Node.js core and more should be supported (and also Apache, Nginx, Caddy server, IIS, ...).

How can we help here with the implementation?

**Comment by CaledoniaProject** [comment]
Thanks DanielRuf, please give us a few weeks to clear the path. Our codebase is mostly in mandarin, I need do some translation and refactoring job before we can start the development :-)

**Comment by DanielRuf** [comment]
> Our codebase is mostly in mandarin, I need do some translation and refactoring job before we can start the development

👍 Unfortunately I do not understand Mandarin so I can not help much with this =(

**Comment by CaledoniaProject** [comment]
I've completed the first step, replaced all alarm messages with English ones. The next release should work for English speakers. Going to write some wiki and plans.

P.S I've created slack space here [OpenRASP Developers](https://openrasp.slack.com/), we can talk here.
