### ISSUE TITLE
PHP7.2 下测试用例拦截后log中没有相关记录信息，这样正常么？

### ISSUE THREAD

**Issue by foxhunter** [baidu/openrasp#149]
手动在PHP7.2环境下安装上了openrasp，且测试用例也能正常拦截。后查看日志发现日志文件中【plugin】【policy】有相关日志文件产生，但是alarm等文件中没有日志。请问这是正常的么？

**Comment by CaledoniaProject** [comment]
你好，请加下QQ群259318664。是不是没有写权限？

**Comment by CaledoniaProject** [comment]
增加FAQ: http://localhost:4000/install/manual/php.html#faq-5

是因为 open_basedir 限制了 php stream 的权限，导致无法写入日志
