### ISSUE TITLE
排除对部分域名的报警检测

### ISSUE THREAD

**Issue by Zer00n** [baidu/openrasp#150]
使用的PHP环境，包含多个域名，其中一个域名使用weiphp，在正常使用中需要file write到缓存的目录中，所以在splunk里查看就看到很多此类警告信息，能否过滤掉单独域名的类型检测那？

**Comment by CaledoniaProject** [comment]
你好，请参考 https://rasp.baidu.com/doc/dev/official.html#case-2

将 action 设置为 ignore 即可

**Comment by CaledoniaProject** [comment]
白名单功能可以等到  1.0 之后增加，写缓存的问题我们会多找几个应用测试下，看看如何处理比较恰当

**Comment by CaledoniaProject** [comment]
我们也发现类似问题了，包括 larvael 框架。所以在 v0.41 里，fileWrite 默认改为 ignore 了。
白名单计划按照检测算法 + URL前缀方式过滤，1.0 RC 3 之前加入支持。
