### ISSUE TITLE
SQLi - Detected dangerous method call char() in sql query 疑问

### ISSUE THREAD

**Issue by Zer00n** [baidu/openrasp#163]
在一个业务中有3个功能，基本类似，都是通过客户端上传excl到服务端，然后执行sql把excl导入到mssql里。但其中两个功能好用，第三个功能就被拦截爆出SQLi - Detected dangerous method call char() in sql query。
经过查看规则发现如下：
if (features['function_blacklist'] && i > 0 && tokens_lc[i][0] === '(')
                {
                    var func_name = tokens_lc[i - 1]

                    if (func_list[func_name]) {
                        reason = _("SQLi - Detected dangerous method call %1%() in sql query", [func_name])
                        break
                    }
                }
            // 盲注函数，如有误报可删掉一些函数
            hex:              true,
            char:             true,
            chr:              true,
            mid:              true,
            ord:              true,
            ascii:            true,
            bin:              true
应该是触发了盲注char()。

两端sql如下：

前两个功能，还用的： 
IF EXISTS ( SELECT  1              FROM    dbo.sysobjects              WHERE   id = OBJECT_ID(N'[dbo].[DegreeReportTempTable]')                      AND OBJECTPROPERTY(id, N'IsUserTable') = 1 )      DROP TABLE dbo.DegreeReportTempTable  CREATE TABLE dbo.DegreeReportTempTable      (        [ExamStuNum] [VARCHAR](50) NULL ,        [ISREPORT] [VARCHAR](10) NULL ,        [REPORTDATE] [VARCHAR](10) NULL ,        [UserID] [VARCHAR](20) NULL ,        [ProcessState] [CHAR](4) NULL ,        [ProcessLog] [VARCHAR](100) NULL      ) 

第三个功能，不好用的sql：
 IF EXISTS (  		SELECT 1  		FROM dbo.sysobjects  		WHERE id = object_id(N'[dbo].[DegreeDiplomaTempTable]')  			AND OBJECTPROPERTY(id, N'IsUserTable') = 1  		)  	DROP TABLE dbo.DegreeDiplomaTempTable    CREATE TABLE dbo.DegreeDiplomaTempTable (  	[ExamStuNum] [varchar](50) NULL,  	[SendFlag] [varchar](10) NULL,  	[SendTime] [varchar](10) NULL,  	[NOSendReason] [varchar](500) NULL,  	[UserID] [varchar](20) NULL,  	[ProcessState] [char](4) NULL,  	[ProcessLog] [varchar](100) NULL  	) 

求解，谢谢~

**Comment by CaledoniaProject** [comment]
你是不是用的老版本，我这边看插件做了小写转换

```
            // 转换小写，避免大小写绕过
            var tokens_lc = raw_tokens.map(function(v) {
                return v.text.toLowerCase()
            })
```

具体请加入 QQ群讨论吧 https://rasp.baidu.com/#section-support

**Comment by CaledoniaProject** [comment]
奇怪了，我这边测试第三个语句不会报警。因为解析出来的 token 并没有 `char` 函数调用。。

**Comment by Zer00n** [comment]
是老版本的，0.4版，这个是创建临时表，因为char就被拦截了。  你是直接测试的语句么？ @CaledoniaProject

**Comment by CaledoniaProject** [comment]
@Zer00n 那可能以前的sqlparser或者JS插件有bug，我这边测试tokenize之后没有char

```
IF EXISTS ( SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[DegreeDiplomaTempTable]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1 ) DROP TABLE dbo.DegreeDiplomaTempTable CREATE TABLE dbo.DegreeDiplomaTempTable ( [ExamStuNum] varchar NULL, [SendFlag] varchar NULL, [SendTime] varchar NULL, [NOSendReason] varchar NULL, [UserID] varchar NULL, [ProcessState] char NULL, [ProcessLog] varchar NULL )
```

**Comment by Zer00n** [comment]
@CaledoniaProject  嗯  我也升级到最新版看看。  十分感谢！
