### ISSUE TITLE
提议一个新的Reponse类需求

### ISSUE THREAD

**Issue by chaojidachanmao** [baidu/openrasp#165]
我最近在给单位设计csp策略的部署工作
是否团队官方考虑增加一个功能Context 类对应的Reponse类
如果能监控输出的内容值，我就能获取输出的标签值 统一成一个nonce
等等其他相关的数据内容安全监控都能使用这个类进行设定 然后用js实现安全逻辑

**Comment by CaledoniaProject** [comment]
你好，不是很理解你的想法。CSP可以用report-uri方法监控，不是很清楚响应body的用途。请加入QQ群联系群主 https://rasp.baidu.com/#section-support 讨论

**Comment by CaledoniaProject** [comment]
长时间没有回应，关闭 ISSUE。
