### ISSUE TITLE
xss-demo.js不起作用

### ISSUE THREAD

**Issue by kunki** [baidu/openrasp#167]
我将`xss-demo.js`放入`<tomcat_home>/rasp/plugins`，同时在`<tomcat_home>/rasp/conf/rasp.properties`中设置了`request.param_encoding=utf-8`，但是仍然无法拦截XXS攻击。

通过插件日志发现获取到的`context.parameter`为`{}`，因而插件检测逻辑不起作用。

请问除了设置`request.param_encoding=utf-8`之外，我还要做什么操作才能获取到不为空的`context.parameter`？

我的OpenRasp版本是1.0.0 RC1
业务代码如下：
```
@RestController
@RequestMapping("/mgr/xxs")
public class XxsController {

    @RequestMapping(value = "/comment.json", method = RequestMethod.POST)
    @ResponseBody
    public String addComment(String comment) {
        return ReturnEnum.SUCCESS.toJSONString("comment", comment);
    }

}
```

**Comment by CaledoniaProject** [comment]
你好，那个插件已经不需要了。1.0 正式版已经支持反射xss检测，计划3月底发布。

**Comment by kunki** [comment]
好的，期待！
顺道借问一下，1.0 正式版的Java版还会支持慢查询的检测吗？

**Comment by CaledoniaProject** [comment]
慢查询因为拿不到SQL语句，所以暂时干掉了。其他问题可以加入QQ群讨论，这样效率更高。

https://rasp.baidu.com/#section-support
