### ISSUE TITLE
使用MyBatis测试SQL注入失败

### ISSUE THREAD

**Issue by kunki** [baidu/openrasp#169]
Mybatis的Mapper为：
```
    <select id="fetchById" resultMap="person">
        SELECT id, nick_name, age, country
        FROM users
        WHERE id = ${personId}
    </select>
```
参数为
`/demo/personId=123%20AnD%201100=1100%20AnD%201100=1101%20--%20`

排查原因发现Mybatis自动将生成的SQL语句的空格去掉了，导致用户输入不再是SQL语句的一部分，从而绕过了检测逻辑。

打印params.query得到的结果（注意缺少最后一个空格）：
```
SELECT id, nick_name, age, country
FROM users
WHERE id = 123 AnD 1100=1100 AnD 1100=1100 --
```

**Comment by CaledoniaProject** [comment]
可以通过修改hook点来解决，目前正在处理，预计 v1.1 修复

**Comment by CaledoniaProject** [comment]
@kunki 你好，v1.3 已经发布并增加了HQL检测点，可以测试了
