### ISSUE TITLE
Show error while running bee pack command

### ISSUE THREAD

**Issue by ask664** [baidu/openrasp#179]
# Bug report
./main.go:30:24: cannot use &controllers.ErrorController literal (type *controllers.ErrorController) as type "github.com/astaxie/beego".ControllerInterface in argument to "github.com/astaxie/beego".ErrorController:
	*controllers.ErrorController does not implement "github.com/astaxie/beego".ControllerInterface (wrong type for Init method)
		have Init(*"rasp-cloud/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})
		want Init(*"github.com/astaxie/beego/context".Context, string, string, interface {})

**Comment by CaledoniaProject** [comment]
Use [build-cloud.sh](https://github.com/baidu/openrasp/blob/master/build-cloud.sh) to build the panel server and frontend.

**Comment by ask664** [comment]
when I run this command - build-cloud.sh then showing me this error.
# github.com/beego/bee/cmd/commands/run
src/github.com/beego/bee/cmd/commands/run/watch.go:88: undefined: time.Until
# github.com/beego/bee/cmd/commands/dlv
src/github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:230: undefined: time.Until
