### ISSUE TITLE
openRasp block requeste after that not able to do further any action in application, not able access

### ISSUE THREAD

**Issue by ask664** [baidu/openrasp#181]
when openRasp block request then I got a log in alarm directory and after that, I restart PHP and apache2 both but not able or access to PHP application.

**Comment by CaledoniaProject** [comment]
You're unable to make a request to your Apache + PHP module server, when OpenRASP successfully blocked a request?

Are you using OpenRASP v1.1.1?

**Comment by ask664** [comment]
yes

**Comment by CaledoniaProject** [comment]
I believe we've resolved this issue in Google Groups, closing this one.

**Comment by ask664** [comment]
yeah but I think you need to update in next release change in plugin.js that all action change from block to log :smile:

**Comment by CaledoniaProject** [comment]
Hmm, It's "log by default" since release 1.0.0, take a look at the `all_log` variable.
