### ISSUE TITLE
agent 信息

### ISSUE THREAD

**Issue by paylm** [baidu/openrasp#183]
# Bug report
同一台主机上，部署多个jetty应用，引用同一路径的rasp agent包时。
在agent 管理界面只显示最新一个上报的应用信息，无法同时显示多个应用。

And please include the following information:
-   CentOS release 6.10 (Final)
-  jetty(8.1.8)
  - java1.8
- OpenRASP version（1.1.2）

# Feature Request
在（Agent 管理） 能同时显示一台主机上的多个应用。

**Comment by CaledoniaProject** [comment]
你好，目前 RASP ID 是根据主机名、网卡、**RASP安装路径** 等几个参数计算出来的。当多个应用使用同一个rasp根目录，就会出现这个现象。

另外，放在一个目录也就意味着日志也放到了一起，可能会出现问题

P.S: 有其他问题可以去QQ群问，这样比较快。 https://rasp.baidu.com/#section-support
