### ISSUE TITLE
Code inside plugin.register function is not executed

### ISSUE THREAD

**Issue by rewanth1997** [baidu/openrasp#185]
# Bug report

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to get execute openrasp. I installed it both on PHP and java applications. I expected the application to log the malicious requests but its not working. I tried both on PHP and java applications. The code inside `plugin.register` function isn't being executed.

I was testing on the standard test-cases recommended by baidu-security team for testing. [https://github.com/baidu-security/openrasp-testcases/blob/master/java/vulns/src/main/webapp/002-file-read.jsp](https://github.com/baidu-security/openrasp-testcases/blob/master/java/vulns/src/main/webapp/002-file-read.jsp)

```
// Inside plugins/888-block-all.js

plugin.register('readFile', function (params, context) {
    plugin.log('inside readFile module')
    return default_action
})
...
plugin.log ('all intercept plugin test: initial success')
```

The second log statement is being saved to an output file but the first log statement is not getting saved because that function isn't getting triggered.

And please include the following information:
- Operating system type and architecture
Ubuntu 18.04
- Application server type and version
Machine1: PHP 7.2
Machine2: openjdk 1.8.0_222, apache tomcat 8.5.45 & tomcat 9.0.24 (tried with multiple versions)

- OpenRASP version
v1.2.0 (7c1eee5)

I added a custom plugin to `$TOMCAT_PATH/rasp/plugins` [https://github.com/baidu/openrasp/blob/master/plugins/addons/888-block-all.js](https://github.com/baidu/openrasp/blob/master/plugins/addons/888-block-all.js) to block all requests, to confirm that openrasp is able to block the requests. But I don't see any output written to alarm.log file.

[https://github.com/baidu/openrasp/blob/master/plugins/addons/888-block-all.js#L37](https://github.com/baidu/openrasp/blob/master/plugins/addons/888-block-all.js#L37) logs the readFile vulnerability to alarm.log while [https://github.com/baidu/openrasp/blob/master/plugins/addons/888-block-all.js#L76](https://github.com/baidu/openrasp/blob/master/plugins/addons/888-block-all.js#L76) logs the plugin initialization values to plugin.log

My application is able to log the plugin initilization information to plugin.log but its not able to trigger the alerts/block requests and alarm.log is empty always.
```
root@f017d0df9d00:/opt/tomcat/apache-tomcat-8.5.45/rasp/logs# tail plugin/plugin.log -n 4
2019-09-09 17:25:28,142 INFO  [INotify thread][com.baidu.openrasp.plugin.js.log] [official] OpenRASP official plugin: Initialized, version 2019-0828-1100
2019-09-09 17:25:28,143 INFO  [INotify thread][com.baidu.openrasp.plugin.js.log] [block-all-test] all intercept plugin test: initial success
2019-09-09 17:25:31,921 INFO  [main][com.baidu.openrasp.plugin.js.log] [official] OpenRASP official plugin: Initialized, version 2019-0828-1100
2019-09-09 17:25:31,924 INFO  [main][com.baidu.openrasp.plugin.js.log] [block-all-test] all intercept plugin test: initial success
```

I edited the conf/openrasp.yml to add custom headers like X-Download-Options, etc and everything is working good.
```
root@f017d0df9d00:/opt/tomcat/apache-tomcat-8.5.45/rasp/logs# curl 127.0.0.1:8082/vulns/002-file-read.jsp -I -L
HTTP/1.1 200
X-Protected-By: OpenRASP
X-Request-ID: 59c2eef5e3b24cc299718eb01ae37a98
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Download-Options: noopen
Set-Cookie: JSESSIONID=79BA23F296362A5CABCC0E84FAC7B14F; Path=/vulns; HttpOnly
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 09 Sep 2019 17:28:01 GMT
```

Any suggestions?

**Comment by CaledoniaProject** [comment]
Please upload your plugin somewhere for us to test. And make sure there's no syntax error in plugin.log.

**Comment by rewanth1997** [comment]
I attached the logs in the above message. The plugin got loaded successfully with no errors.

```
2019-09-09 17:25:31,924 INFO  [main][com.baidu.openrasp.plugin.js.log] [block-all-test] all intercept plugin test: initial success
```

I will upload the link to a zip file of the plugin soon.

**Comment by rewanth1997** [comment]
Use the following dockerfile and following commands to reproduce this issue.

```
rewanth@ubuntu:/tmp/openrasp$ cat Dockerfile
FROM tomcat:8.0
MAINTAINER OpenRASP Developers

ARG version_testcase
ENV version_testcase=${version_testcase:-v1.0.8}

ARG version_rasp
ENV version_rasp=${version_rasp:-v0.40}

ENV TOMCAT_HOME /usr/local/tomcat
ENV PATH $TOMCAT_HOME/bin:$PATH

ADD "https://github.com/baidu-security/openrasp-testcases/releases/download/v1.0.8/vulns.war" /usr/local/tomcat/webapps
ADD "https://github.com/baidu/openrasp/releases/download/v0.40/rasp-java.tar.gz" /tmp/rasp-java.tar.gz

RUN cd /tmp \
        && tar -zxvf rasp-java.tar.gz \
        && java -jar rasp-*/RaspInstall.jar -install "$TOMCAT_HOME"

ADD "https://gist.github.com/rewanth1997/cda4ade40f7ac7a84e710c9e63c5b951/raw/4ca4801fd2ca376bb45d9f87888029b87d0a81bb/888-block-all.js" /usr/local/tomcat/rasp/plugins/888-block-all.js
RUN rm /usr/local/tomcat/rasp/plugins/official.js

EXPOSE 8080
```

Build the image locally
```
rewanth@ubuntu:/tmp/openrasp$ docker build . -t test/openrasp
```

```
rewanth@ubuntu:/tmp/openrasp$ docker run -p8080:8080 -it test/openrasp bash
root@ed4295680c3c:/usr/local/tomcat#./bin/startup.sh
```

The server is running now. When I visit a sensitive endpoint, error should be triggered and the page should be blocked but instead I get a clear 200 response instead of 302.
```
root@ed4295680c3c:/usr/local/tomcat# curl localhost:8080/vulns/001-dir-1.jsp?dirname=../../../../../../../../../../../../../../../var/log/ -I
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Protected-By: OpenRASP
X-Request-ID: 544a5c69c1b945bebfb3185d09b1b9f2
Set-Cookie: JSESSIONID=6E12CB78F3E709D50D6FDCEB1E20BD49; Path=/vulns; HttpOnly
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 16 Sep 2019 09:31:47 GMT
```

**Comment by CaledoniaProject** [comment]
The key name `Action` should be in lowercase:

```
const default_action = {
    Action: 'block',
    Message: '- plugin all intercept test-',
    Confidence: 90
}
```

**Comment by rewanth1997** [comment]
I was using google chrome and it auto-translated the script from Chinese to English.
Ref: [https://raw.githubusercontent.com/baidu/openrasp/master/plugins/addons/888-block-all.js](https://raw.githubusercontent.com/baidu/openrasp/master/plugins/addons/888-block-all.js)

The google translator changed the case of variables resulting in unexpected behavior.

I think it would be better if openrasp can log a plugin error if no action is specified in the return object. The `action` should be either log, block or ignore. In this case, there is no `action` variable specified, so it didn't perform any operation returning 200 response. Your views on this recommendation?

**Comment by spacelan** [comment]
In this case, it should log a empty message:

https://github.com/baidu-security/openrasp-v8/blob/76a25b54cbe48b0ff87ac9470b677af62599942c/base/js/rasp.js#L80

Sorry for confusing you, but this behavior is by design

**Comment by rewanth1997** [comment]
I think it would be better if a default message like `default behavior` or some relevant message is saved to openrasp logs. As of now the message is an empty string, the log file size was zero and debugging is a real pain.

In case of auto-assignment of values a simple default message in logs will be really helpful. At least the user/developer will be sure that openrasp is working and there is some error in their custom plugin. Your views?
