### ISSUE TITLE
alpine系统不兼容问题

### ISSUE THREAD

**Issue by cc88cc** [baidu/openrasp#188]
# Bug report
现很多企业采用docker 集群部署微服务，alpine 系统只有几M大小，公司大多采用alpine系统作为docker 基础镜像。当前openrasp部署在alpine上出现不兼容问题，有没有什么解决方法或折中方案？

**Comment by spacelan** [comment]
还是支持的，不过没有发布预编译版本

如果有人写了alpine上的构建脚本欢迎提PR

**Comment by windghoul** [comment]
alpine 编译openrasp-v8 出现大量错误，请问有没有编译好的alpine 版本的openrasp-v8 包？

**Comment by spacelan** [comment]
预编译的动态库将在1.3.3版本加入jar包，之后可以直接在alpine上部署

详细信息：https://github.com/baidu-security/openrasp-v8/issues/8
