### ISSUE TITLE
请问能否提供mac环境下源码构建的文档

### ISSUE THREAD

**Issue by shidongwa** [baidu/openrasp#192]
# Feature Request

Please replace this section with:
- https://rasp.baidu.com/doc/hacking/compile/java.html已经提供了linux环境下的源代码构建的文档描述，请问能否提供mac book下对应的步骤。很多开发者都是mac环境，相应的gcc，cmake没有一个标准的步骤。多谢。

**Comment by CaledoniaProject** [comment]
你好，build-java.sh 能够在 mac 下执行

**Comment by shidongwa** [comment]
响应好快！开发IDE不开心了。
