### ISSUE TITLE
Build Bug

### ISSUE THREAD

**Issue by imsatender** [baidu/openrasp#197]
# Bug report

I am trying to build the php7 extension but getting the error

<pre>/bin/bash /var/www/html/ctokens/openrasp/agent/php7/libtool --mode=compile g++  -I. -I/var/www/html/ctokens/openrasp/agent/php7 -DPHP_ATOM_INC -I/var/www/html/ctokens/openrasp/agent/php7/include -I/var/www/html/ctokens/openrasp/agent/php7/main -I/var/www/html/ctokens/openrasp/agent/php7 -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/var/www/html/ctokens/openrasp/agent/php7/third_party/yaml-cpp/include  -DHAVE_CONFIG_H  -g -O2 -Wno-narrowing -std=c++11 -Wno-deprecated-declarations -Wno-write-strings -Wno-deprecated-register  -c /var/www/html/ctokens/openrasp/agent/php7/openrasp.cc -o openrasp.lo 
libtool: compile:  g++ -I. -I/var/www/html/ctokens/openrasp/agent/php7 -DPHP_ATOM_INC -I/var/www/html/ctokens/openrasp/agent/php7/include -I/var/www/html/ctokens/openrasp/agent/php7/main -I/var/www/html/ctokens/openrasp/agent/php7 -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/var/www/html/ctokens/openrasp/agent/php7/third_party/yaml-cpp/include -DHAVE_CONFIG_H -g -O2 -Wno-narrowing -std=c++11 -Wno-deprecated-declarations -Wno-write-strings -Wno-deprecated-register -c /var/www/html/ctokens/openrasp/agent/php7/openrasp.cc  -fPIC -DPIC -o .libs/openrasp.o
In file included from <b>/var/www/html/ctokens/openrasp/agent/php7/openrasp_conf_holder.h:23:0</b>,
                 from <b>/var/www/html/ctokens/openrasp/agent/php7/openrasp.h:39</b>,
                 from <b>/var/www/html/ctokens/openrasp/agent/php7/openrasp.cc:20</b>:
<b>/var/www/html/ctokens/openrasp/agent/php7/openrasp_config_block.h:25:10:</b> <font color="#EF2929"><b>fatal error: </b></font>php/header.h: No such file or directory
 #include <font color="#EF2929"><b>&quot;php/header.h&quot;</b></font>
          <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
compilation terminated.
Makefile:195: recipe for target &apos;openrasp.lo&apos; failed
make: *** [openrasp.lo] Error 1
</pre>

**Comment by spacelan** [comment]
How did you start the build, manually or using build-php7.sh?

**Comment by imsatender** [comment]
> How did you start the build, manually or using build-php7.sh?

Using build-php7.sh and also one more issue there is not configure file exists

<pre>Zend Extension Api No:   320151012
+ [[ linux == \m\a\c\o\s ]]
+ ./configure --with-openrasp-v8=/var/www/html/ctokens/openrasp/openrasp-v8/ --with-gettext --enable-openrasp-remote-manager -q
./configure: line 4705: no: command not found
./configure: line 4706: no: command not found
</pre>

**Comment by spacelan** [comment]
Can you upload the full output of build-php7.sh here?

**Comment by CaledoniaProject** [comment]
php-dev is required to build the package

**Comment by imsatender** [comment]
> The error message here is self-explanatory:
> 
> ```
> /var/www/html/ctokens/openrasp/agent/php7/openrasp_config_block.h:25:10: fatal error: php/header.h: No such file or directory
>  #include "php/header.h"
> ```
> 
> php-dev is required to build the package on Ubuntu

Sorry to interrupt you, I have installed all the required packages before sending the error to you guys. This is the error which is coming on 

<pre>No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
</pre>

**Comment by CaledoniaProject** [comment]
I'll leave this issue open but we do not have time to deeply investigate this.

**Comment by imsatender** [comment]
I have fixed it by editing file "/etc/apt/sources.list" and uncomment deb-src for php

**Comment by motikan2010** [comment]
By installing "pkg-config", I'm fix this issue.
```
$ apt install -y pkg-config
```
