### ISSUE TITLE
Support For Opentracing

### ISSUE THREAD

**Issue by imsatender** [baidu/openrasp#198]
Hi,

I am planning to integrate open-tracing with OpenRasp, if you guys can help me on this, it will be helpful. 

https://github.com/opentracing/opentracing-php

https://github.com/opentracing/opentracing-c

So if we can embed tracing in the module itself, it will be performance-oriented for the php community.

Regards,

**Comment by CaledoniaProject** [comment]
Thanks for your suggestion. But I believe opentrace can run without openrasp and we do not have resources for this.

You may fork and create your own branch to do it.
