### ISSUE TITLE
目录遍历问题

### ISSUE THREAD

**Issue by yiwang6** [baidu/openrasp#201]
rasp正常启动时，目录遍历，
如http://10.108.12.77/001-dir.php?dir=/proc 拦截
http://10.108.12.77/001-dir.php?dir=/ 拦截
http://10.108.12.77/001-dir.php?dir=/etc 不拦截
http://10.108.12.77/001-dir.php?dir=/opt 不拦截
http://10.108.12.77/001-dir.php?dir=/tmp  不拦截
没有覆盖全吗？

**Comment by CaledoniaProject** [comment]
你可以改插件哈

**Comment by CaledoniaProject** [comment]
你好，这种问题请在QQ群里讨论 https://rasp.baidu.com/#section-support
