### ISSUE TITLE
建议php7.4

### ISSUE THREAD

**Issue by haoziz** [baidu/openrasp#203]
php7.4已发布有一段时间，建议适配跟上

**Comment by CaledoniaProject** [comment]
已经在计划中，年后会支持

**Comment by haozi-dev** [comment]
感谢回复

**Comment by XMD0718** [comment]
@CaledoniaProject 唔，已经2021年了，原本计划在2020年后支持的PHP7.4还没有开整吗？PHP8.0都出来了的说。。。我很看好这个项目的，加油干啊

**Comment by tinysheepyang** [comment]
强烈要求支持PHP7.4啊，公司马上要上8.0了，用的最低版本7.4，加油加油

**Comment by CaledoniaProject** [comment]
PHP7.4 测试可以编译，预计年后提给QA测试。

**Comment by haoziz** [comment]
> PHP7.4 测试可以编译，预计年后提给QA测试。

php8.0有测试吗？

**Comment by CaledoniaProject** [comment]
7.4 将在 v1.3.7 里支持，已有 beta 版本: https://packages.baidu.com/app/openrasp/release/1.3.7-beta/rasp-php-linux.tar.bz2
