### ISSUE TITLE
Base OS version

### ISSUE THREAD

**Issue by imsatender** [baidu/openrasp#204]
# BASE OS VERSION
Hi,

I want to know what is base Linux os version for generating extensions of PHP5 and PHP7.

Please help me with the same.

**Comment by CaledoniaProject** [comment]
Any recent Linux distribution would do. We release the binary files on CentOS 6.X

**Comment by imsatender** [comment]
Hi,

As per `travis.yaml ` for php 5.4 and 5.6 dist is trusty and for php 7.0 onwards there is no dist defined.

Can you please help on the same, what dist we should use for php 7.0 onwards?

Regards,
Satender K.

**Comment by CaledoniaProject** [comment]
PHP 7.X is also built on CentOS 6.X, with remi repository, e.g https://github.com/baidu-security/app-env-docker/blob/master/src/openrasp-buildenv/php-centos6-php7.0/Dockerfile

**Comment by imsatender** [comment]
Hi @CaledoniaProject ,

I have tried the same but getting error as mentioned below:

`$ docker build -f a .
Sending build context to Docker daemon    449MB
Step 1/5 : FROM openrasp/devtoolset-4
pull access denied for openrasp/devtoolset-4, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by imsatender** [comment]
Hi @CaledoniaProject ,

Can you please send me steps for building the extension for php7.3, it would be very helpful to me using the build process?

Regards,
Satender K.

**Comment by CaledoniaProject** [comment]
@imsatender Take a look at build-php7.sh in the root of the repo
