### ISSUE TITLE
Build Generation

### ISSUE THREAD

**Issue by imsatender** [baidu/openrasp#205]
Hi,

I have one doubt in PHP extension build process, can you please help me out?

Currently, we are generating PHP extension based on the PHP version. Can't we generate a single extension for PHP5 and PHP7 respectively?

Please reply to me on the same

Regards,

**Comment by CaledoniaProject** [comment]
This is by design, PHP won't load modules compiled against different minor versions. It would involve multiple dirty hacks to bypass this mechanism. We have no plan for that.
