### ISSUE TITLE
是否可以用其它数据库替换mongodb，如MySQL 或者 不使用mongodb吗？

### ISSUE THREAD

**Issue by wantaoli** [baidu/openrasp#206]
# Bug report

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions

And please include the following information:
- Operating system type and architecture
- Application server type and version
  - For Java based web application servers, provide JDK version
- OpenRASP version

# Feature Request

Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- what alternatives to the feature you have considered

**Comment by CaledoniaProject** [comment]
你好，这个我们暂无计划，如果一定要换，你可以重写管理后台
