### ISSUE TITLE
这里string用==不会有bug吗？

### ISSUE THREAD

**Issue by chhhaya** [baidu/openrasp#209]
https://github.com/baidu/openrasp/blob/59352ca47cfbad8aa699d11d9d857d5d240aaced/agent/java/boot/src/main/java/com/baidu/openrasp/ModuleLoader.java#L78

**Comment by tangyouyi1513** [comment]
不会有问题，只接受常量

> https://github.com/baidu/openrasp/blob/59352ca47cfbad8aa699d11d9d857d5d240aaced/agent/java/boot/src/main/java/com/baidu/openrasp/Agent.java#L70

> https://github.com/baidu/openrasp/blob/59352ca47cfbad8aa699d11d9d857d5d240aaced/agent/java/boot/src/main/java/com/baidu/openrasp/Agent.java#L80
