### ISSUE TITLE
engine module 运行在 system Classloader怎么来做代码隔离呢

### ISSUE THREAD

**Issue by shidongwa** [baidu/openrasp#211]
# Bug report

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions

And please include the following information:
- Operating system type and architecture
- Application server type and version
  - For Java based web application servers, provide JDK version
- OpenRASP version

# Feature Request

看代码rasp-engine module是通过system ClassLoader加载的，那么怎么隔离open rasp代码和业务代码呢？

**Comment by CaledoniaProject** [comment]
这个问题请加入QQ群讨论吧，https://rasp.baidu.com/#section-support
