### ISSUE TITLE
RASP无法启动

### ISSUE THREAD

**Issue by LimeZky** [baidu/openrasp#214]
在今天尝试启动RASP时，遇到了如图错误
![image](https://user-images.githubusercontent.com/31511420/79642817-48a35380-81d2-11ea-886d-64aa0828236f.png)

**Comment by CaledoniaProject** [comment]
贴文本日志

**Comment by CaledoniaProject** [comment]
看着好像机器内存太小了，目前最低支持 2C/4GB 的虚拟机。
