### ISSUE TITLE
构建脚本build-cloud.sh中环境变量漏了$符号

### ISSUE THREAD

**Issue by zhuxd** [baidu/openrasp#234]
https://github.com/baidu/openrasp/blob/43735d6cd99e570f00abbebf91cfcf37955855f9/build-cloud.sh#L81

应该是：`if [[ -z "$NO_GOMOD_DOWNLOAD" ]]; then`

**Comment by CaledoniaProject** [comment]
你提个PR吧，不过我们切到国内源了也用不到这个了
