### ISSUE TITLE
关于logstash解析rasp日志

### ISSUE THREAD

**Issue by xizhimen** [baidu/openrasp#240]
# Bug report

rasp-cloud 1.3.5

    我们的架构是rasp->kafka->logstash->es
问题在logstash解析kafka日志时，报错如下：
![image](https://user-images.githubusercontent.com/19748550/100955766-16bce280-3552-11eb-8c48-7d64d8dc7726.png)
logstash对unixi这个时间戳解析不了

尝试过从logtash移除这个字段，没成功，干脆修改了源码临时解决，代码改动如下：

dependency.go
![image](https://user-images.githubusercontent.com/19748550/100956071-ac587200-3552-11eb-95d6-da0918753a09.png)

kafka.go
![image](https://user-images.githubusercontent.com/19748550/100956103-b7ab9d80-3552-11eb-9539-3d9588af7b69.png)

不这其他朋友有没有这个问题，如果是共性问题，希望能更新代码！

**Comment by CaledoniaProject** [comment]
https://github.com/baidu/openrasp/commit/a6f89be28abc9db0a645cf93e253cbebc9f0dfc5#diff-8ebf6aa6a079ced04143a92bcd3cbacb8d7bbacac0098eee6124ed4b42e1836bR51
