### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#243]
建议在防护设置增加反序列化黑名单列表手动输入功能
这样做可以参考jackson的黑名单不断维护一个可靠的反序列化黑名单
这样做的好处就是面对新的反序列化攻击可以有效的做到应急响应

建议将Transformer 反序列化 修改为 一个可以手工维护的黑名单列表

**Comment by CaledoniaProject** [comment]
可以，看了下OGNL也没有做成配置，下个版本一起改掉

**Comment by CaledoniaProject** [comment]
![screen 2020-12-25 at 10 05 56](https://user-images.githubusercontent.com/1357701/103114261-d9eb9380-4698-11eb-84b3-b46adea67fe4.jpg)

1.3.6 加上了，等发布的时候需要同时升级插件和后台才会展示。
