### ISSUE TITLE
关于插件中关于fastjson的安全策略加强

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#245]
首先在最新的插件中我们可以观察到fastjson的防护策略只有一条，内容如下：
com.alibaba.fastjson.JSON.parseObject
通过阅读fastjson的代码JSON.parseObject函数实际上调用了JSON.parse
![图片](https://user-images.githubusercontent.com/22064977/103458652-28f29200-4d45-11eb-94d2-73d49bc54a12.png)

那我认为，实际上插件应该也要参照jackson的拦截方法
拦截   method.startsWith(com.alibaba.fastjson.JSON.)

佐证文章：https://www.anquanke.com/post/id/222946  （可以直接看最后的总结 和  parse与parseObject的区别）

**Comment by CaledoniaProject** [comment]
为了保护性能，先简单改下 https://github.com/baidu/openrasp/commit/042fa165b8112464482b0ab4f315b8a335007c5a

**Comment by k4n5ha0** [comment]
关于插件中关于fastjson的安全策略加强

> 为了保护性能，先简单改下 [042fa16](https://github.com/baidu/openrasp/commit/042fa165b8112464482b0ab4f315b8a335007c5a)

今天发现fastjson还有一个parseArray函数，底层没有调用JSON.parseObject或者JSON.parse
建议插件中增加
com.alibaba.fastjson.JSON.parseArray
函数

**Comment by CaledoniaProject** [comment]
已加
