### ISSUE TITLE
sql注入绕过的解决建议

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#252]
我建议在插件中的1889行进行修改
将
`else if (features['version_comment'] && tokens_lc[i][0] === '/' && tokens_lc[i][1] === '*' && tokens_lc[i][2] === '!')`
改为
`else if (features['version_comment'] && tokens_lc[i][0] === '/' && tokens_lc[i][1] === '*' )`

并且进一步建议，完全禁止其他多种类型的sql注释，以避免sql注入的绕过问题
以避免以下的问题
![image](https://user-images.githubusercontent.com/22064977/108993180-2cffb800-76d5-11eb-9801-731218423e8d.png)
![image](https://user-images.githubusercontent.com/22064977/108993193-30933f00-76d5-11eb-9380-763df0d4515e.png)

**Comment by yinhuochong** [comment]
完全block注释会有大量误报，所以默认只检测了正常情况使用少，但注入中更常见的版本号注释
