### ISSUE TITLE
感谢百度,Tomcat 10.0.2部署单机版rasp-2021-03-04后，Tomcat 无法正常关闭cmd窗口

### ISSUE THREAD

**Issue by WenTao-Love** [baidu/openrasp#253]
很惊喜百度能有如此良心的rasp产品，很强大，谢谢！
环境：Oracle jdk 15.0.2
           Windows 7 sp2
Tomcat 10.0.2部署单机版rasp-2021-03-04后，发现Tomcat无法通过shutdown.bat或者Ctrl+C
来正常终止cmd窗口，只能强行点击右上角关闭按钮，进行关闭操作。
谢谢！

**Comment by CaledoniaProject** [comment]
不建议使用openjdk，bug太多了，你还是换oracle的吧。

**Comment by WenTao-Love** [comment]
> 不建议使用openjdk，bug太多了，你还是换oracle的吧。

感谢回复，我是使用oracle官方的jdk。

**Comment by CaledoniaProject** [comment]
用 catalina.cmd 测试
