### ISSUE TITLE
请问我怎么添加国产数据库sql注入监测呢？

### ISSUE THREAD

**Issue by WenTao-Love** [baidu/openrasp#254]
感谢百度，感谢OpenRASP!
现在公司要求数据库逐步采用国产数据库，比如达梦，阿里db。
因此，我想添加国产数据库sql注入监测？
是添加新的插件吗？

**Comment by CaledoniaProject** [comment]
参考源代码，增加hook点

**Comment by WenTao-Love** [comment]
> 参考源代码，增加hook点

好的，收到。
