### ISSUE TITLE
支持自动从路径中选择版本最高版本rasp-engine

### ISSUE THREAD

**Issue by jekkay** [baidu/openrasp#256]
背景：编译好的两个jar包名字固定为, rasp-engine, rasp，如果每次都给两个jar包给业务，又没有显式的版本信息，很容易弄混。
期待支持特性：
 1. 允许编译好的jar包名字带有版本信息，如： rasp-engine-1.3.6.jar, rasp-1.3.6.jar
 2. 如果在目录路径下有多个rasp-engine，则自动选择版本最高的jar

# Feature Request

Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- what alternatives to the feature you have considered

**Comment by CaledoniaProject** [comment]
如之前微信沟通，这个需求完全可以通过启动参数来解决
