### ISSUE TITLE
建议HTTP 响应采样检测添加一个检测 pass  password passwd的功能

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#259]
![image](https://user-images.githubusercontent.com/22064977/111954938-d050bb00-8b23-11eb-850a-0a0b5f5e01df.png)

因为实际场景中，等级保护测试渗透测试等测试中，检测response的内容中禁止出现password字段十分严格，建议openrasp添加该功能

**Comment by CaledoniaProject** [comment]
这个太容易误报了，比如 `<input type="password">`。

如果有需求可以自行修改插件，在这个地方加上你自己逻辑就可以了:

```
plugin.register('response', function (params, context) {
```
