### ISSUE TITLE
php7 build zend_smart_str.h: No such file or directory

### ISSUE THREAD

**Issue by forgottor** [baidu/openrasp#262]
In file included from ./hook/data/raw_material.h:21:0,
                 from ./hook/data/v8_material.h:19,
                 from /root/openrasp/agent/php7/hook/checker/v8_detector.h:20,
                 from /root/openrasp/agent/php7/openrasp.cc:23:
./openrasp_hook.h:50:10: fatal error: zend_smart_str.h: No such file or directory
 #include "zend_smart_str.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [openrasp.lo] 错误 1

php73 -v
PHP 7.3.27 (cli) (built: Feb  2 2021 10:32:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies

**Comment by CaledoniaProject** [comment]
仅支持 build-php7.sh 编译

**Comment by forgottor** [comment]
使用 build-php7.sh编译的啊

**Comment by CaledoniaProject** [comment]
php headers 不对
