### ISSUE TITLE
Resources should be closed

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [baidu/openrasp#265]
https://github.com/baidu/openrasp/blob/f992962207bec063eda6fb908b08d1548f21e3df/agent/java/engine/src/main/java/com/baidu/openrasp/dependency/DependencyFinder.java#L140-L156
Use try-with-resources or close this "FileOutputStream" in a "finally" clause.

**Comment by CaledoniaProject** [comment]
收到，确实是个问题，将在 v.1.3.7 修复

**Comment by CaledoniaProject** [comment]
https://github.com/baidu/openrasp/commit/2485bb29b23004d19ae96af8e4c858d4311cd1be
