### ISSUE TITLE
增加一个策略的探讨

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#275]
https://landgrey.me/blog/22/

上文是hw期间出现的一个手法，我在想，rasp模式是否限制：禁止写入当前java目录jar后缀的文件。
期望请官方和各位爱好者讨论下。

**Comment by xuing** [comment]
感觉应该是HIPS做的事情。

**Comment by k4n5ha0** [comment]
> 感觉应该是HIPS做的事情。

hids？

**Comment by k4n5ha0** [comment]
我对比了下，和网防g01比起来，其实网防g01就是多了一个网页防篡改的功能，所以可以直接在网防g01上设置不可写路径以规避这个攻击手段，所以这个风险还是使用防篡改更加适宜。

**Comment by k4n5ha0** [comment]
> 感觉应该是HIPS做的事情。

说的对，禁止对java进程的目录进行写操作就行了。
