### ISSUE TITLE
问题 ：xalan.internal.xsltc.trax.TemplatesImpl黑名单是否有误

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#278]
咨询官方一个问题：
    // transformer 反序列化攻击
    deserialization_blacklist: {
        name:   '算法1 - 反序列化黑名单过滤',
        action: 'block',
		clazz: [
            'org.apache.commons.collections.functors.ChainedTransformer.transform',
            'org.apache.commons.collections.functors.InvokerTransformer',
            'org.apache.commons.collections.functors.InstantiateTransformer',
            'org.apache.commons.collections4.functors.InvokerTransformer',
            'org.apache.commons.collections4.functors.InstantiateTransformer',
            'org.codehaus.groovy.runtime.ConvertedClosure',
            'org.codehaus.groovy.runtime.MethodClosure',
            'org.springframework.beans.factory.ObjectFactory',
            'xalan.internal.xsltc.trax.TemplatesImpl'
        ]
    }
其中的“xalan.internal.xsltc.trax.TemplatesImpl” 
是否应该改为
“com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl”

谢谢

**Comment by CaledoniaProject** [comment]
应该是这样，你可以提个PR

**Comment by CaledoniaProject** [comment]
https://github.com/baidu/openrasp/commit/abb22e6d3a1b6b6505d3da30d2e33a2152c4f094
