### ISSUE TITLE
新版XXE的修复逻辑遗漏

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#282]
https://www.anquanke.com/post/id/241107
依照上文，我发现其中提到一种方式的paylaod：
file:../../../../../../../../etc/passwd

![image](https://user-images.githubusercontent.com/22064977/122851269-3e826500-d341-11eb-9235-9445eafef37e.png)

![image](https://user-images.githubusercontent.com/22064977/122851103-ffecaa80-d340-11eb-9f1d-133dbb2dd6db.png)

payload是
```
http://XXXX/vulns/007-xxe-stax.jsp?data=<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [   <!ELEMENT foo ANY >  <!ENTITY xxe SYSTEM "file:../../../../../etc/passwd" >]><foo>&xxe;</foo>
```

**Comment by CaledoniaProject** [comment]
已处理 https://github.com/baidu/openrasp/blob/master/plugins/official/plugin.js#L2896
