### ISSUE TITLE
openrasp XXE规则绕过

### ISSUE THREAD

**Issue by xsser** [baidu/openrasp#288]
规则的编写。。似乎设计了白名单，遇到.xml文件就不检测。
故XXE漏洞中去访问 file:///etc/passwd#.xml就可以绕过。
测试过，可以读取

**Comment by CaledoniaProject** [comment]
你好，请提供下测试用例、JDK版本、应用服务器版本

**Comment by xsser** [comment]
jdk1.8
测试用力就是

file:///etc/passwd#.xml

**Comment by CaledoniaProject** [comment]
需要你提供下受影响的XML类库

**Comment by xsser** [comment]
SAXReader啥的  忘记了。。

**Comment by CaledoniaProject** [comment]
我们成功复现了，不只是`#`，会尽快修复

**Comment by xsser** [comment]
> 我们成功复现了，不只是`#`，会尽快修复

能申请一个cve么？

**Comment by CaledoniaProject** [comment]
已修复 https://github.com/baidu/openrasp/blob/master/plugins/official/plugin.js#L2906
