### ISSUE TITLE
openrasp  SQL注入规则4 ReDos

### ISSUE THREAD

**Issue by xsser** [baidu/openrasp#291]
大哥我提交了这么几个绕过+dos 能帮忙申请一个cve来刷个kpi么？

sql_regex: {
        name:      '算法4 - 正则表达式算法',
        action:    'ignore',
        regex:     'union.*select.*from.*information_schema'
    }

开启sql_regex 算法4规则的时候，
这个regex会存在dos，应该就会挂了。。。
麻烦帮忙试试申请一个cve?

**Comment by CaledoniaProject** [comment]
你好，这个算法只是个例子，默认是不开的。现在检测SQL注入并不用正则，这个只是应急用的，如果有人想加正则，可以直接后台配置，就不用改算法了。

已在后台增加提示并修改了默认值，多谢反馈

![screenshot 2021-06-26 at 7 20 33 AM](https://user-images.githubusercontent.com/1357701/123493496-223b3c80-d64f-11eb-9338-5b177d7c6c40.jpg)

**Comment by xsser** [comment]
ok！
