### ISSUE TITLE
代码冗杂重复

### ISSUE THREAD

**Issue by jinhaoxin** [baidu/openrasp#295]
https://github.com/baidu/openrasp/blob/ec46a2c16cd5c358b1b132138e3bc1f5acc4f122/plugins/official/plugin.js#L1215

![image](https://user-images.githubusercontent.com/40516116/124727128-03875080-df41-11eb-859d-3c08fdbadf9d.png)
两个函数代码完全一致

**Comment by yinhuochong** [comment]
https://github.com/baidu/openrasp/commit/7beabf783bef945444cb2c0e76210b970dd3c4eb 已删除
