### ISSUE TITLE
official.js中定义了is_from_userinput()函数两次

### ISSUE THREAD

**Issue by killer1278** [baidu/openrasp#296]
![image](https://user-images.githubusercontent.com/18377502/125243131-3e61fd80-e320-11eb-912e-27e0596d287c.png)

**Comment by CaledoniaProject** [comment]
你好，这个问题别人提交过，已经修复了哈。后面再有发现代码问题，请先检查master分支是否已经修复哈。
 
https://github.com/baidu/openrasp/issues/295 
https://github.com/baidu/openrasp/commit/7beabf783bef945444cb2c0e76210b970dd3c4eb

**Comment by killer1278** [comment]
哦哦，不好意思啊
