### ISSUE TITLE
暂不支持国产web容器tongweb7

### ISSUE THREAD

**Issue by xinglongZeng** [baidu/openrasp#317]
-- rasp版本:1.3.6
-- tongweb版本: 7
 tongweb7版本由于与rasp已经集成的tongweb版本差异较大（主要是agent部分），现无法支持新版本的tongweb （tongweb7及其以上版本）。
       目前本地已经适配了tongweb7的agent，请允许提交push或其他处理方式。

**Comment by CaledoniaProject** [comment]
已合入1.3.7分支。目前QA正在测试java版本，预计元旦后2周发版 https://github.com/baidu/openrasp/pull/318
