### ISSUE TITLE
类名错误

### ISSUE THREAD

**Issue by liangyixiki** [baidu/openrasp#324]
https://github.com/baidu/openrasp/blob/0412db88abe2503df02a0f65a67af985a86223d9/plugins/official/plugin.js#L556
黑名单中的类名是不是因该是
”org.apache.commons.collections.functors.ChainedTransformer “不是 ”org.apache.commons.collections.functors.ChainedTransformer.transform“

**Comment by yinhuochong** [comment]
fixed https://github.com/baidu/openrasp/commit/dd7a1089d6f42307b010e07886a9f414f1345752
