### ISSUE TITLE
shiro的CommonsBeanutils1和CommonsBeanutils2链分析

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#340]
CommonsBeanutils1链
![image](https://user-images.githubusercontent.com/22064977/156914005-f32f9602-7d70-4cac-a015-e7157d5be4bf.png)
org.apache.commons.beanutils.BeanComparator

![image](https://user-images.githubusercontent.com/22064977/156914032-e8575125-8809-4d35-9abd-9b52bcac2c22.png)
org.apache.commons.collections.comparators.ComparableComparator

CommonsBeanutils2链
![image](https://user-images.githubusercontent.com/22064977/156914074-b8119670-e1ae-4a32-9a35-17ed3abb5e14.png)
org.apache.commons.beanutils.BeanComparator

![image](https://user-images.githubusercontent.com/22064977/156914089-e9c67d39-d004-4f7f-b654-8fb7bfeb9215.png)
org.apache.commons.beanutils.BeanComparator

综上所述：
建议把
org.apache.commons.beanutils.BeanComparator
放入全局的反序列化黑名单之内

**Comment by CaledoniaProject** [comment]
你是说加到resolveClass检查里？

**Comment by k4n5ha0** [comment]
> 你是说加到resolveClass检查里？

嗯，deserialization_blacklist之内
