### ISSUE TITLE
一个关于dockerfile安装的小的需求

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#351]
![image](https://user-images.githubusercontent.com/22064977/160517819-ab18569e-ae55-4218-99b6-945ac7db7bff.png)
将上图中的jdk路径和tomcat路径如下图标红并提示，这样大家就知道需要修改哪里了
![image](https://user-images.githubusercontent.com/22064977/160517854-53aad41e-78d5-43e2-8997-a7b65ff9ee32.png)

**Comment by CaledoniaProject** [comment]
![1](https://user-images.githubusercontent.com/1357701/160519964-ad91045c-3ba4-4b6e-aeb8-a9b85ffe11cc.jpg)
