### ISSUE TITLE
请问这里传给doCheck方法的参数为什么是EMPTY_MAP呢，这不是没检测吗？

### ISSUE THREAD

**Issue by Strang** [baidu/openrasp#36]
https://github.com/baidu/openrasp/blob/6b9b417ad8a731c2b2e7c733bdfca5a83fcf6add/agent/java/src/main/java/com/fuxi/javaagent/HookHandler.java#L224

**Comment by CaledoniaProject** [comment]
[因为 request hook 点，params 参数是空的](https://rasp.baidu.com/doc/dev/data.html)
