### ISSUE TITLE
# Feature Request 增加struts2的ognl表达式长度的安全策略

### ISSUE THREAD

**Issue by k4n5ha0** [baidu/openrasp#369]
# Feature Request
- 增加对st2的ognl表达式长度的安全策略，官方文档建议不要超过400
![image](https://user-images.githubusercontent.com/22064977/168468050-636f8fb3-b3f4-4ff6-b32c-ce4cabfbda10.png)

- 主要是为了防护未知的新0day，目前经过压缩的最新exp长度为709
- 我考虑过很多方案，还给官方提pr，官方对默认长度限制也不是很积极，我觉得可以设置400为限制，如果超过了400则按照当前模式进行拦截过或者打一条日志

**Comment by CaledoniaProject** [comment]
你可以写个算法，struts ognl语句超过400就直接阻断，可以提个PR

**Comment by CaledoniaProject** [comment]
已合入
