### ISSUE TITLE
对agent传递过来的环境变量敏感信息进行打码或不显示

### ISSUE THREAD

**Issue by heywiorld** [baidu/openrasp#392]
# Feature Request

Please replace this section with:
- 当agent安装完毕后，会向server端发送env环境变量并在service端进行显示，由于agent的env部分可能包括比较敏感的内容，比如密码等，所以想对敏感部分进行打码或不发送这部分内容。
- 出于agent端env可能包含敏感信息考虑
- 暂无其他可替代品

**Comment by nicolas-zheng** [comment]
在spring boot世界，不要把密码写到环境变量，包一个HashMap就可以隐藏这些细节类似这样

 protected Map<String, String> environmentVariableMap = new HashMap(System.getenv());

**Comment by heywiorld** [comment]
> 在spring boot世界，不要把密码写到环境变量，包一个HashMap就可以隐藏这些细节类似这样
> 
> protected Map<String, String> environmentVariableMap = new HashMap(System.getenv());

好的 非常感谢
