### ISSUE TITLE
敏感信息的逻辑错误，无法过滤非html、json、xml的response

### ISSUE THREAD

**Issue by ddpang** [baidu/openrasp#418]
https://github.com/baidu/openrasp/blob/7beabf783bef945444cb2c0e76210b970dd3c4eb/plugins/official/plugin.js#L3119

应该把逻辑与改为逻辑或

逻辑与的问题：content-type为application/javascript时，无法直接return clean
我们预想的结果应该是：正则匹配失败时return clean，正则匹配成功不return clean

**Comment by CaledoniaProject** [comment]
这个确实有问题，可以提交个PR
