### ISSUE TITLE
rasp fail to start! unable to connect to mongo

### ISSUE THREAD

**Issue by QscvGYU** [baidu/openrasp#423]
配置app.conf mongo 无论是 无认证 还是 账号密码 在log中都是 ubable to connect to mongodb server：no reachable servers。
我用另一台电脑使用 MongoDBCompass 链接都没有问题。 mongodbname  填不填都报这个

**Comment by fooevr** [comment]
+1

**Comment by CaledoniaProject** [comment]
mongodb版本太高或者账号密码不对

**Comment by QscvGYU** [comment]
我试了一下 是因为mongo的版本太高了，建议在readme里面 加一下支持的mongo版本。这个issue关了吧
