### ISSUE TITLE
rasp死锁导致业务不可用

### ISSUE THREAD

**Issue by ddpang** [baidu/openrasp#450]
与[#435提交的issues](https://github.com/baidu/openrasp/issues/435)一样，我们也遇到了死锁问题。死锁位置System.getProperty("java.version")
总结：rasp一切获取锁的地方都可能与，主代码里懒加载的类死锁。
我们的解决方案：rasp获取锁的相关代码，前移至agent启动阶段并缓存，避开与业务的冲突

**Comment by CaledoniaProject** [comment]
合到master了，你得自己编译一下

**Comment by kindragos** [comment]
@ddpang 
你的方案，覆盖的范围看起来更大，可以详细说一下你们的修改点么？ 
或者有PR么？想学习一下。
