### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [baidu/openrasp#457]
Greetings maintainers of openrasp,

Github Security Lab has found a potential vulnerability in openrasp. We have attempted to email openrasp-support@baidu.com but did not receive a response. Please let us know where we can disclose security issues at.  If you don't currently have a way to receive such issues, we recommend [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

Thank you,
Kevin 

# Bug report
All details will be in submitted report.

**Comment by CaledoniaProject** [comment]
It somehow went to the spambox, I've replied to your email.
