### ISSUE TITLE
rasp-vue   本地起不起来

### ISSUE THREAD

**Issue by yangdonbin** [baidu/openrasp#461]
**拉下来官方源码
node  /  npm 版本分别是：8.9.4   /   **5.6.0**
运行 
1.npm install      
2.npm run start**
大概查了一下，好像是package.json的依赖冲突，自己弄了半天，实在弄不好，修复了这个冲突，又会导致别的地方出问题

![image](https://github.com/baidu/openrasp/assets/75525530/cd1319c3-dff2-4ee5-b706-f59a0cb02f62)

**Comment by CaledoniaProject** [comment]
没在windows下试过，估计跟你的node版本有关
