### ISSUE TITLE
有没有对resin容器的支持？

### ISSUE THREAD

**Issue by sancao2** [baidu/openrasp#61]
除了Tomcat，Jetty，JBoss，SpringBoot，有没有对resin容器的支持？
支持的话，有文档吗？

**Comment by CaledoniaProject** [comment]
目前没有，我们评估下

**Comment by CaledoniaProject** [comment]
@sancao2 你使用的 resin 是哪个版本？官网有 3.X，2.X 和 EE 是三个

**Comment by sancao2** [comment]
我们现在用的是比较老的3.1.8。@CaledoniaProject

**Comment by CaledoniaProject** [comment]
好的，收到

**Comment by CaledoniaProject** [comment]
@sancao2 你用的 JDK 版本是多少?

**Comment by sancao2** [comment]
jdk6

**Comment by sancao2** [comment]
JDK 1.7，好像是开源的resin 3.1，我还在确认。不好意思，我前段时间比较忙。一个人的安全部。。。。

**Comment by CaledoniaProject** [comment]
好的

**Comment by sancao2** [comment]
不好意思，我今天提交辞职了。我打算再家里蹲看看书吧。resin，应该是下个版本出来。出来，我自己试用一下吧。
还有我测过tomcat 9也是兼容的。

**Comment by CaledoniaProject** [comment]
这两天发版，在 v0.31 里增加了 Resin 3.X，4.X 的支持
